### ISSUE TITLE
Don't require dev-master version of Raven

### ISSUE THREAD

**Issue by tremby** [clowdy/laravel-raven#11]
Is there no stable release with the features required? Requiring a moving target like dev-master can causes things to break unexpectedly when a new backwards-incompatible commit appears in the dependency. The dependency should at least be fixed to a particular commit, like `dev-master#247c4e5faf0b2b8cd9de7ad30ddf7b044bdc89a6`

**Comment by pulkitjalan** [comment]
Currently there is no stable release on Raven with the features required. I am planning on making more PR's that should fix the test. Once thats done and they have released a version, ill fix it on here. I wont be releasing a version of `laravel-raven` that requires `dev-master` as a dependency.

**Comment by Stayallive** [comment]
@pulkitjalan `laravel-raven` 2.1.* requires `dev-master` op `raven/raven`. Is there still not a release mature enough?

**Comment by threesquared** [comment]
:+1: for this. Would be nice to track stable releases.

**Comment by pulkitjalan** [comment]
done, tracking `~0.13`
